// Generated by scripts/update-registry.mjs from registry.json. Do not edit by hand.
import type { ComponentType } from "react";
import { Avatar } from "@/registry/components/avatar";
import { Badge } from "@/registry/components/badge";
import { Banner } from "@/registry/components/banner";
import { Blockquote } from "@/registry/components/blockquote";
import { BottomSheet } from "@/registry/components/bottom-sheet";
import { Breadcrumb } from "@/registry/components/breadcrumb";
import { Button } from "@/registry/components/button";
import { Card } from "@/registry/components/card";
import { Carousel } from "@/registry/components/carousel";
import { CodeBlock } from "@/registry/components/code-block";
import { Footer } from "@/registry/blocks/footer";
import { FooterMinimal } from "@/registry/blocks/footer-minimal";
import { FooterStacked } from "@/registry/blocks/footer-stacked";
import { Kbd } from "@/registry/components/kbd";
import { Login } from "@/registry/blocks/login";
import { LoginMinimal } from "@/registry/blocks/login-minimal";
import { LoginSplit } from "@/registry/blocks/login-split";
import { Navbar } from "@/registry/blocks/navbar";
import { NavbarAligned } from "@/registry/blocks/navbar-aligned";
import { NavbarFloating } from "@/registry/blocks/navbar-floating";
import { Pricing } from "@/registry/blocks/pricing";
import { PricingCompact } from "@/registry/blocks/pricing-compact";
import { PricingComparison } from "@/registry/blocks/pricing-comparison";
import { SmeBackground } from "@/registry/shader/sme-background";
import { Table } from "@/registry/components/table";
import { Tabs } from "@/registry/components/tabs";

export const previewEntries: Record<string, { component: ComponentType; category: "components" | "blocks" | "shader" }> = {
  "avatar": { component: Avatar, category: "components" },
  "badge": { component: Badge, category: "components" },
  "banner": { component: Banner, category: "components" },
  "blockquote": { component: Blockquote, category: "components" },
  "bottom-sheet": { component: BottomSheet, category: "components" },
  "breadcrumb": { component: Breadcrumb, category: "components" },
  "button": { component: Button, category: "components" },
  "card": { component: Card, category: "components" },
  "carousel": { component: Carousel, category: "components" },
  "code-block": { component: CodeBlock, category: "components" },
  "footer": { component: Footer, category: "blocks" },
  "footer-minimal": { component: FooterMinimal, category: "blocks" },
  "footer-stacked": { component: FooterStacked, category: "blocks" },
  "kbd": { component: Kbd, category: "components" },
  "login": { component: Login, category: "blocks" },
  "login-minimal": { component: LoginMinimal, category: "blocks" },
  "login-split": { component: LoginSplit, category: "blocks" },
  "navbar": { component: Navbar, category: "blocks" },
  "navbar-aligned": { component: NavbarAligned, category: "blocks" },
  "navbar-floating": { component: NavbarFloating, category: "blocks" },
  "pricing": { component: Pricing, category: "blocks" },
  "pricing-compact": { component: PricingCompact, category: "blocks" },
  "pricing-comparison": { component: PricingComparison, category: "blocks" },
  "sme-background": { component: SmeBackground, category: "shader" },
  "table": { component: Table, category: "components" },
  "tabs": { component: Tabs, category: "components" },
};
