// Generated by scripts/update-registry.mjs from registry.json. Do not edit by hand.
import type { ComponentType } from "react";
import { AuroraVeil } from "@/registry/shader/aurora-veil";
import { ContactFooter } from "@/registry/blocks/contact-footer";
import { ContourDrift } from "@/registry/shader/contour-drift";
import { DaylightAtlas } from "@/registry/blocks/daylight-atlas";
import { DitherField } from "@/registry/shader/dither-field";
import { EditorialNavbar } from "@/registry/blocks/editorial-navbar";
import { Interference } from "@/registry/shader/interference";
import { KineticTypeLab } from "@/registry/components/kinetic-type-lab";
import { ListeningStation } from "@/registry/blocks/listening-station";
import { MagicLinkSignIn } from "@/registry/blocks/magic-link-sign-in";
import { NewsletterFooter } from "@/registry/blocks/newsletter-footer";
import { OrbitSelector } from "@/registry/components/orbit-selector";
import { PortfolioNavbar } from "@/registry/blocks/portfolio-navbar";
import { PrismRibbon } from "@/registry/shader/prism-ribbon";
import { SeasonTimeline } from "@/registry/components/season-timeline";
import { SecretTicket } from "@/registry/components/secret-ticket";
import { SignalDial } from "@/registry/components/signal-dial";
import { SocialSignIn } from "@/registry/blocks/social-sign-in";
import { SplitSignIn } from "@/registry/blocks/split-sign-in";
import { StorefrontFooter } from "@/registry/blocks/storefront-footer";
import { StorefrontNavbar } from "@/registry/blocks/storefront-navbar";
import { StudioFooter } from "@/registry/blocks/studio-footer";
import { StudioHero } from "@/registry/blocks/studio-hero";
import { StudioNavbar } from "@/registry/blocks/studio-navbar";
import { WorkspaceSignUp } from "@/registry/blocks/workspace-sign-up";

export const previewEntries: Record<string, { component: ComponentType; category: "components" | "blocks" | "shader" }> = {
  "aurora-veil": { component: AuroraVeil, category: "shader" },
  "contact-footer": { component: ContactFooter, category: "blocks" },
  "contour-drift": { component: ContourDrift, category: "shader" },
  "daylight-atlas": { component: DaylightAtlas, category: "blocks" },
  "dither-field": { component: DitherField, category: "shader" },
  "editorial-navbar": { component: EditorialNavbar, category: "blocks" },
  "interference": { component: Interference, category: "shader" },
  "kinetic-type-lab": { component: KineticTypeLab, category: "components" },
  "listening-station": { component: ListeningStation, category: "blocks" },
  "magic-link-sign-in": { component: MagicLinkSignIn, category: "blocks" },
  "newsletter-footer": { component: NewsletterFooter, category: "blocks" },
  "orbit-selector": { component: OrbitSelector, category: "components" },
  "portfolio-navbar": { component: PortfolioNavbar, category: "blocks" },
  "prism-ribbon": { component: PrismRibbon, category: "shader" },
  "season-timeline": { component: SeasonTimeline, category: "components" },
  "secret-ticket": { component: SecretTicket, category: "components" },
  "signal-dial": { component: SignalDial, category: "components" },
  "social-sign-in": { component: SocialSignIn, category: "blocks" },
  "split-sign-in": { component: SplitSignIn, category: "blocks" },
  "storefront-footer": { component: StorefrontFooter, category: "blocks" },
  "storefront-navbar": { component: StorefrontNavbar, category: "blocks" },
  "studio-footer": { component: StudioFooter, category: "blocks" },
  "studio-hero": { component: StudioHero, category: "blocks" },
  "studio-navbar": { component: StudioNavbar, category: "blocks" },
  "workspace-sign-up": { component: WorkspaceSignUp, category: "blocks" },
};
